telegram_bot:
  - platform: polling
    api_key: 12341234:xxxxxxxxxxxxxxxxx
    allowed_chat_ids:
      - 1111111
      - -111111

notify:
  - name: MyTelegram
    platform: telegram
    chat_id: 1111111
  - name: EthMinersTelegram
    platform: telegram
    chat_id: -1111111
    

sensor:
  - platform: rest
    resource: http://xyzxyz.ethosdistro.com/?json=yes
    name: ethos
    value_template: '{{ value_json.total_hash }}'